cwlVersion: v1.0
class: CommandLineTool

hints:
  DockerRequirement:
    dockerPull: quay.io/biocontainers/hhsuite:3.3.0--py39pl5321h67e14b5_5

baseCommand: python3

inputs:
  script:
    type: File
    default:
      class: File
      location: /scistor/informatica/hwt330/cwl-epitope/tools/run_hhblits.py
  protein_query_sequences:
    type: File
    default:
      class: File
      location: /scistor/informatica/hwt330/cwl-epitope/test.fasta # change this later
    # format: FASTA protein
    doc: |
      "File with FASTA sequences for which HHM profiles will be generated by HHBlits"
  database:
    type: Directory
    default:
      class: Directory
      location: /scistor/informatica/hwt330/hhblits/databases
    doc: |
      "Directory containing hhblits databases"
  database_name:
    type: string
    default: "pdb70"
    doc: |
      "The database against which to run the query protein sequence, must be located in $(inputs.database)"
  output_directory_name:
    type: string
    default: "hhm_features" 
    doc: |
      "Name of directory in which output .hhm files will be stored."

# python3 
# run_hhblits.py 
# /scistor/informatica/hwt330/cwl-epitope/test.fasta 
# /scistor/informatica/hwt330/hhblits/databases/pdb70 
# --outdir 
# ./test_out

arguments:
  - $(inputs.script.path)
  - $(inputs.protein_query_sequences.path)
  - $(inputs.database.path)/$(inputs.database_name)
  - --outdir
  - ./$(inputs.output_directory_name)

outputs:
  hhm_profiles: 
    type: Directory
    outputBinding:
      glob: ./$(inputs.output_directory_name)
    doc: |
      "Directory containing HHM profiles for each of the input protein sequences."
    # format: https://github.com/soedinglab/hh-suite/wiki#file-formats (.hhm)


